/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as DashboardRouteImport } from './routes/dashboard.tsx'
import { Route as AssetsRouteImport } from './routes/assets.tsx'
import { Route as AnalyticsRouteImport } from './routes/analytics.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as BuilderIndexRouteImport } from './routes/builder/index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns/$campaignId.tsx'
import { Route as BuilderVideoRouteImport } from './routes/builder/video.tsx'
import { Route as ApiTeamMembersRouteImport } from './routes/api.teamMembers.ts'
import { Route as ApiDashboardChartsRouteImport } from './routes/api.dashboardCharts.ts'
import { Route as ApiCampaignsRouteImport } from './routes/api.campaigns.ts'
import { Route as ApiAdvertisersRouteImport } from './routes/api.advertisers.ts'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs.tsx'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request.tsx'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names.ts'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index.tsx'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode.tsx'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr.tsx'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only.tsx'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/builder/',
  path: '/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderVideoRoute = BuilderVideoRouteImport.update({
  id: '/builder/video',
  path: '/builder/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamMembersRoute = ApiTeamMembersRouteImport.update({
  id: '/api/teamMembers',
  path: '/api/teamMembers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardChartsRoute = ApiDashboardChartsRouteImport.update({
  id: '/api/dashboardCharts',
  path: '/api/dashboardCharts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvertisersRoute = ApiAdvertisersRouteImport.update({
  id: '/api/advertisers',
  path: '/api/advertisers',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/api/advertisers': typeof ApiAdvertisersRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/dashboardCharts': typeof ApiDashboardChartsRoute
  '/api/teamMembers': typeof ApiTeamMembersRoute
  '/builder/video': typeof BuilderVideoRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/builder': typeof BuilderIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/api/advertisers': typeof ApiAdvertisersRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/dashboardCharts': typeof ApiDashboardChartsRoute
  '/api/teamMembers': typeof ApiTeamMembersRoute
  '/builder/video': typeof BuilderVideoRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/builder': typeof BuilderIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/api/advertisers': typeof ApiAdvertisersRoute
  '/api/campaigns': typeof ApiCampaignsRoute
  '/api/dashboardCharts': typeof ApiDashboardChartsRoute
  '/api/teamMembers': typeof ApiTeamMembersRoute
  '/builder/video': typeof BuilderVideoRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/builder/': typeof BuilderIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assets'
    | '/dashboard'
    | '/api/advertisers'
    | '/api/campaigns'
    | '/api/dashboardCharts'
    | '/api/teamMembers'
    | '/builder/video'
    | '/campaigns/$campaignId'
    | '/builder'
    | '/campaigns'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assets'
    | '/dashboard'
    | '/api/advertisers'
    | '/api/campaigns'
    | '/api/dashboardCharts'
    | '/api/teamMembers'
    | '/builder/video'
    | '/campaigns/$campaignId'
    | '/builder'
    | '/campaigns'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assets'
    | '/dashboard'
    | '/api/advertisers'
    | '/api/campaigns'
    | '/api/dashboardCharts'
    | '/api/teamMembers'
    | '/builder/video'
    | '/campaigns/$campaignId'
    | '/builder/'
    | '/campaigns/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssetsRoute: typeof AssetsRoute
  DashboardRoute: typeof DashboardRoute
  ApiAdvertisersRoute: typeof ApiAdvertisersRoute
  ApiCampaignsRoute: typeof ApiCampaignsRoute
  ApiDashboardChartsRoute: typeof ApiDashboardChartsRoute
  ApiTeamMembersRoute: typeof ApiTeamMembersRoute
  BuilderVideoRoute: typeof BuilderVideoRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/': {
      id: '/builder/'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/video': {
      id: '/builder/video'
      path: '/builder/video'
      fullPath: '/builder/video'
      preLoaderRoute: typeof BuilderVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teamMembers': {
      id: '/api/teamMembers'
      path: '/api/teamMembers'
      fullPath: '/api/teamMembers'
      preLoaderRoute: typeof ApiTeamMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboardCharts': {
      id: '/api/dashboardCharts'
      path: '/api/dashboardCharts'
      fullPath: '/api/dashboardCharts'
      preLoaderRoute: typeof ApiDashboardChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advertisers': {
      id: '/api/advertisers'
      path: '/api/advertisers'
      fullPath: '/api/advertisers'
      preLoaderRoute: typeof ApiAdvertisersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssetsRoute: AssetsRoute,
  DashboardRoute: DashboardRoute,
  ApiAdvertisersRoute: ApiAdvertisersRoute,
  ApiCampaignsRoute: ApiCampaignsRoute,
  ApiDashboardChartsRoute: ApiDashboardChartsRoute,
  ApiTeamMembersRoute: ApiTeamMembersRoute,
  BuilderVideoRoute: BuilderVideoRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
  BuilderIndexRoute: BuilderIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
