/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthResetpasswordRouteImport } from './routes/auth/resetpassword'
import { Route as AuthForgotpasswordRouteImport } from './routes/auth/forgotpassword'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as AuthenticatedProjectsProjectIdEditRouteImport } from './routes/_authenticated/projects/$projectId/edit'
import { Route as AuthenticatedDemoStartServerFuncsRouteImport } from './routes/_authenticated/demo/start.server-funcs'
import { Route as AuthenticatedDemoStartApiRequestRouteImport } from './routes/_authenticated/demo/start.api-request'
import { Route as AuthenticatedDemoApiNamesRouteImport } from './routes/_authenticated/demo/api.names'
import { Route as AuthenticatedDemoStartSsrIndexRouteImport } from './routes/_authenticated/demo/start.ssr.index'
import { Route as AuthenticatedDemoStartSsrSpaModeRouteImport } from './routes/_authenticated/demo/start.ssr.spa-mode'
import { Route as AuthenticatedDemoStartSsrFullSsrRouteImport } from './routes/_authenticated/demo/start.ssr.full-ssr'
import { Route as AuthenticatedDemoStartSsrDataOnlyRouteImport } from './routes/_authenticated/demo/start.ssr.data-only'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetpasswordRoute = AuthResetpasswordRouteImport.update({
  id: '/auth/resetpassword',
  path: '/auth/resetpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotpasswordRoute = AuthForgotpasswordRouteImport.update({
  id: '/auth/forgotpassword',
  path: '/auth/forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedProjectsProjectIdEditRoute =
  AuthenticatedProjectsProjectIdEditRouteImport.update({
    id: '/$projectId/edit',
    path: '/$projectId/edit',
    getParentRoute: () => AuthenticatedProjectsRoute,
  } as any)
const AuthenticatedDemoStartServerFuncsRoute =
  AuthenticatedDemoStartServerFuncsRouteImport.update({
    id: '/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoStartApiRequestRoute =
  AuthenticatedDemoStartApiRequestRouteImport.update({
    id: '/demo/start/api-request',
    path: '/demo/start/api-request',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoApiNamesRoute =
  AuthenticatedDemoApiNamesRouteImport.update({
    id: '/demo/api/names',
    path: '/demo/api/names',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoStartSsrIndexRoute =
  AuthenticatedDemoStartSsrIndexRouteImport.update({
    id: '/demo/start/ssr/',
    path: '/demo/start/ssr/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoStartSsrSpaModeRoute =
  AuthenticatedDemoStartSsrSpaModeRouteImport.update({
    id: '/demo/start/ssr/spa-mode',
    path: '/demo/start/ssr/spa-mode',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoStartSsrFullSsrRoute =
  AuthenticatedDemoStartSsrFullSsrRouteImport.update({
    id: '/demo/start/ssr/full-ssr',
    path: '/demo/start/ssr/full-ssr',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemoStartSsrDataOnlyRoute =
  AuthenticatedDemoStartSsrDataOnlyRouteImport.update({
    id: '/demo/start/ssr/data-only',
    path: '/demo/start/ssr/data-only',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/demo/api/names': typeof AuthenticatedDemoApiNamesRoute
  '/demo/start/api-request': typeof AuthenticatedDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/demo/start/ssr/data-only': typeof AuthenticatedDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof AuthenticatedDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof AuthenticatedDemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof AuthenticatedDemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof AuthenticatedIndexRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/demo/api/names': typeof AuthenticatedDemoApiNamesRoute
  '/demo/start/api-request': typeof AuthenticatedDemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/demo/start/ssr/data-only': typeof AuthenticatedDemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof AuthenticatedDemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof AuthenticatedDemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof AuthenticatedDemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/auth/forgotpassword': typeof AuthForgotpasswordRoute
  '/auth/resetpassword': typeof AuthResetpasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/demo/api/names': typeof AuthenticatedDemoApiNamesRoute
  '/_authenticated/demo/start/api-request': typeof AuthenticatedDemoStartApiRequestRoute
  '/_authenticated/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
  '/_authenticated/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/demo/start/ssr/data-only': typeof AuthenticatedDemoStartSsrDataOnlyRoute
  '/_authenticated/demo/start/ssr/full-ssr': typeof AuthenticatedDemoStartSsrFullSsrRoute
  '/_authenticated/demo/start/ssr/spa-mode': typeof AuthenticatedDemoStartSsrSpaModeRoute
  '/_authenticated/demo/start/ssr/': typeof AuthenticatedDemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/auth/forgotpassword'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/projects/new'
    | '/projects/'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/projects/$projectId/edit'
    | '/projects/$projectId/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/forgotpassword'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/projects/new'
    | '/projects'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/projects/$projectId/edit'
    | '/projects/$projectId'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/projects'
    | '/auth/forgotpassword'
    | '/auth/resetpassword'
    | '/auth/signin'
    | '/auth/signup'
    | '/_authenticated/'
    | '/_authenticated/projects/new'
    | '/_authenticated/projects/'
    | '/_authenticated/demo/api/names'
    | '/_authenticated/demo/start/api-request'
    | '/_authenticated/demo/start/server-funcs'
    | '/_authenticated/projects/$projectId/edit'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/demo/start/ssr/data-only'
    | '/_authenticated/demo/start/ssr/full-ssr'
    | '/_authenticated/demo/start/ssr/spa-mode'
    | '/_authenticated/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthForgotpasswordRoute: typeof AuthForgotpasswordRoute
  AuthResetpasswordRoute: typeof AuthResetpasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/resetpassword': {
      id: '/auth/resetpassword'
      path: '/auth/resetpassword'
      fullPath: '/auth/resetpassword'
      preLoaderRoute: typeof AuthResetpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgotpassword': {
      id: '/auth/forgotpassword'
      path: '/auth/forgotpassword'
      fullPath: '/auth/forgotpassword'
      preLoaderRoute: typeof AuthForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/projects/$projectId/edit': {
      id: '/_authenticated/projects/$projectId/edit'
      path: '/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEditRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/demo/start/server-funcs': {
      id: '/_authenticated/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof AuthenticatedDemoStartServerFuncsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/start/api-request': {
      id: '/_authenticated/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof AuthenticatedDemoStartApiRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/api/names': {
      id: '/_authenticated/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof AuthenticatedDemoApiNamesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/start/ssr/': {
      id: '/_authenticated/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof AuthenticatedDemoStartSsrIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/start/ssr/spa-mode': {
      id: '/_authenticated/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof AuthenticatedDemoStartSsrSpaModeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/start/ssr/full-ssr': {
      id: '/_authenticated/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof AuthenticatedDemoStartSsrFullSsrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo/start/ssr/data-only': {
      id: '/_authenticated/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof AuthenticatedDemoStartSsrDataOnlyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedProjectsProjectIdEditRoute: typeof AuthenticatedProjectsProjectIdEditRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedProjectsProjectIdEditRoute:
    AuthenticatedProjectsProjectIdEditRoute,
  AuthenticatedProjectsProjectIdIndexRoute:
    AuthenticatedProjectsProjectIdIndexRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemoApiNamesRoute: typeof AuthenticatedDemoApiNamesRoute
  AuthenticatedDemoStartApiRequestRoute: typeof AuthenticatedDemoStartApiRequestRoute
  AuthenticatedDemoStartServerFuncsRoute: typeof AuthenticatedDemoStartServerFuncsRoute
  AuthenticatedDemoStartSsrDataOnlyRoute: typeof AuthenticatedDemoStartSsrDataOnlyRoute
  AuthenticatedDemoStartSsrFullSsrRoute: typeof AuthenticatedDemoStartSsrFullSsrRoute
  AuthenticatedDemoStartSsrSpaModeRoute: typeof AuthenticatedDemoStartSsrSpaModeRoute
  AuthenticatedDemoStartSsrIndexRoute: typeof AuthenticatedDemoStartSsrIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemoApiNamesRoute: AuthenticatedDemoApiNamesRoute,
  AuthenticatedDemoStartApiRequestRoute: AuthenticatedDemoStartApiRequestRoute,
  AuthenticatedDemoStartServerFuncsRoute:
    AuthenticatedDemoStartServerFuncsRoute,
  AuthenticatedDemoStartSsrDataOnlyRoute:
    AuthenticatedDemoStartSsrDataOnlyRoute,
  AuthenticatedDemoStartSsrFullSsrRoute: AuthenticatedDemoStartSsrFullSsrRoute,
  AuthenticatedDemoStartSsrSpaModeRoute: AuthenticatedDemoStartSsrSpaModeRoute,
  AuthenticatedDemoStartSsrIndexRoute: AuthenticatedDemoStartSsrIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthForgotpasswordRoute: AuthForgotpasswordRoute,
  AuthResetpasswordRoute: AuthResetpasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
